name: Update Wiki with New Problems

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Wiki Repository
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki-repo

      - name: Generate Wiki Pages
        run: |
          mkdir -p wiki-repo  # Ensure the folder exists
          node .github/scripts/updateWiki.js  # Run the script to generate wiki pages

      - name: Push Changes to Wiki
        run: |
          cd wiki-repo
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update wiki with new problems" || echo "No changes to commit"
          git push || echo "No changes to push"
